INSERT INTO question_answers (question_id, answer_text, option_id, created_at, updated_at)
VALUES
(3, 'Keiko' , null ,  NOW(), NOW()),
(11, 'JO6337' , null ,  NOW(), NOW()),
(15, 'Advanced English studies', null ,  NOW(), NOW()),
(17, '5 months', null ,  NOW(), NOW()),
(19, 'About 4 months', null ,  NOW(), NOW()),
(21, null, 2 ,  NOW(), NOW()),
(21, null, 4 ,  NOW(), NOW()),
(23, 'Seafood', null ,  NOW(), NOW()),
(24, 'Tennis', null ,  NOW(), NOW()),
(25, 'Take the train', null ,  NOW(), NOW()),
(27, '90 days', null ,  NOW(), NOW()),
(28, '30 pounds', null ,  NOW(), NOW()),
(29, 'Confirm your nationality', null ,  NOW(), NOW()),
(30, 'Page 13', null ,  NOW(), NOW()),
(32, 'Currency form', null ,  NOW(), NOW()),
(33, 'Tourist export form', null ,  NOW(), NOW()),
(34, 'BM276', null ,  NOW(), NOW()),
(38, 'International student card ', null ,  NOW(), NOW()),
(37, '12', null ,  NOW(), NOW()),
(39, 'Australian dollar', null ,  NOW(), NOW()),
(41, 'Cashier', null ,  NOW(), NOW()),
(42, '£50', null ,  NOW(), NOW()),
(43, 'Big department stores', null ,  NOW(), NOW()),
(44, 'Jeans', null ,  NOW(), NOW()),
(54, '45 pounds', null ,  NOW(), NOW()),
(56, '75 pounds', null ,  NOW(), NOW()),
(58, '20 pounds', null ,  NOW(), NOW()),
(60, null , 8 ,  NOW(), NOW()),
(60, null , 9 ,  NOW(), NOW()),
(60, null , 10 ,  NOW(), NOW()),
(62, null , 12 ,  NOW(), NOW()),
(63, null , 16 ,  NOW(), NOW()),
(64, null , 19 ,  NOW(), NOW()),
(65, null , 25 ,  NOW(), NOW()),
(66, null , 30 ,  NOW(), NOW()),
(67, null , 33 ,  NOW(), NOW()),
(68, null , 38 ,  NOW(), NOW()),
(69, null , 39 ,  NOW(), NOW()),
(70, null , 43 ,  NOW(), NOW()),
(71, null , 47 ,  NOW(), NOW());
