INSERT INTO question_answers (question_id, answer_text, option_id, created_at, updated_at)
VALUES
(363, '3' , null ,  NOW(), NOW()),
(365, 'brakes' , null ,  NOW(), NOW()),
(367, 'going overseas', null ,  NOW(), NOW()),
(369, '$1500', null ,  NOW(), NOW()),
(371, '6:30 pm', null ,  NOW(), NOW()),
(373, '88 Princess Street', null ,  NOW(), NOW()),
(377, null, 226 ,  NOW(), NOW()),
(378, null, 230 ,  NOW(), NOW()),
(379, null, 233 ,  NOW(), NOW()),
(380, null, 234 ,  NOW(), NOW()),
(388, '3 hours', null ,  NOW(), NOW()),
(389, 'grey whales', null ,  NOW(), NOW()),
(390, 'hot springs', null ,  NOW(), NOW()),
(399, 'fast, playful, curious', null ,  NOW(), NOW()),
(401, 'black and white', null ,  NOW(), NOW()),
(406, '14 meters', null ,  NOW(), NOW()),
(409, 'in the middle', null ,  NOW(), NOW()),
(410, 'orange', null ,  NOW(), NOW()),
(411, 'can not swim', null ,  NOW(), NOW()),
(412, 'at the wrist', null ,  NOW(), NOW()),
(414, '200', null ,  NOW(), NOW()),
(415, '4 week', null ,  NOW(), NOW()),
(416, '8', null ,  NOW(), NOW()),
(419, '10 minute video', null ,  NOW(), NOW()),
(420, 'film making', null ,  NOW(), NOW()),
(421, 'travel plan', null ,  NOW(), NOW()),
(423, null, 239 ,  NOW(), NOW()),
(424, null, 241 ,  NOW(), NOW()),
(426, 'April', null ,  NOW(), NOW()),
(427, 'course, flights', null ,  NOW(), NOW()),
(429, null , 243 ,  NOW(), NOW()),
(430, null , 248 ,  NOW(), NOW()),
(431, null , 250 ,  NOW(), NOW()),
(433, 'keyboard', null ,  NOW(), NOW()),
(434, '70%', null ,  NOW(), NOW()),
(435, '50 words', null ,  NOW(), NOW()),
(436, 'accuracy', null ,  NOW(), NOW()),
(437, 'speed', null ,  NOW(), NOW()),
(438, '12 to 20', null ,  NOW(), NOW()),
(440, null , 254 ,  NOW(), NOW()),
(442, null, 257 ,  NOW(), NOW()),
(444, 'NO' , null ,  NOW(), NOW()),
(445, 'NO', null ,  NOW(), NOW()),
(446, 'YES', null ,  NOW(), NOW()),
(447, 'NOT GIVEN', null ,  NOW(), NOW()),
(448, 'NO', null ,  NOW(), NOW()),
(451, 'F', null ,  NOW(), NOW()),
(452, 'B', null ,  NOW(), NOW()),
(453, 'E', null ,  NOW(), NOW()),
(455, 'safety', null ,  NOW(), NOW()),
(456, 'not on duty', null ,  NOW(), NOW()),
(458, null, 261 ,  NOW(), NOW()),
(459, null, 264 ,  NOW(), NOW()),
(462, 'v', null ,  NOW(), NOW()),
(463, 'vii', null ,  NOW(), NOW()),
(464, 'viii', null ,  NOW(), NOW()),
(465, 'x', null ,  NOW(), NOW()),
(466, 'iii', null ,  NOW(), NOW()),
(467, 'ix', null ,  NOW(), NOW()),
(469, 'alcohol and water', null ,  NOW(), NOW()),
(470, 'shaken', null ,  NOW(), NOW()),
(471, 'stronger', null ,  NOW(), NOW()),
(473, 'heal itself', null ,  NOW(), NOW()),
(474, 'control symptoms', null ,  NOW(), NOW()),
(475, 'cheaper', null ,  NOW(), NOW()),
(476, 'side effects', null ,  NOW(), NOW()),
(493, 'F', null ,  NOW(), NOW()),
(494, 'A', null ,  NOW(), NOW()),
(495, 'E', null ,  NOW(), NOW()),
(496, 'B', null ,  NOW(), NOW()),
(497, 'D', null ,  NOW(), NOW()),
(504, 'low quality', null ,  NOW(), NOW()),
(506, 'no THC', null ,  NOW(), NOW()),
(510, 'A', null ,  NOW(), NOW()),
(511, 'B', null ,  NOW(), NOW()),
(512, 'A', null ,  NOW(), NOW()),
(513, 'C', null ,  NOW(), NOW()),
(514, 'A', null ,  NOW(), NOW()),
(515, 'C', null ,  NOW(), NOW()),
(517, null, 267 ,  NOW(), NOW());
