INSERT INTO question_answers (question_id, answer_text, option_id, created_at, updated_at)
VALUES
(246, '80', null ,  NOW(), NOW()),
(248, 'maximum limit', null ,  NOW(), NOW()),
(250, '4.5', null ,  NOW(), NOW()),
(251, 'Hire and installation', null ,  NOW(), NOW()),
(253, 'carpeting', null ,  NOW(), NOW()),
(256, '55', null ,  NOW(), NOW()),
(262, 'June 5th', null ,  NOW(), NOW()),
(266, 'Jenny Lakewell', null ,  NOW(), NOW()),
(268, 'CV6TL3', null ,  NOW(), NOW()),
(270, '07944325883', null ,  NOW(), NOW()),
(273, 'G', null ,  NOW(), NOW()),
(274, 'D', null ,  NOW(), NOW()),
(275, 'C', null ,  NOW(), NOW()),
(276, 'A', null ,  NOW(), NOW()),
(277, 'F', null ,  NOW(), NOW()),
(279, null , 160 ,  NOW(), NOW()),
(280, null , 163 ,  NOW(), NOW()),
(281, null , 167 ,  NOW(), NOW()),
(282, null , 168 ,  NOW(), NOW()),
(283, null , 173 ,  NOW(), NOW()),
(285, null , 175 ,  NOW(), NOW()),
(286, null , 179 ,  NOW(), NOW()),
(287, null , 182 ,  NOW(), NOW()),
(288, null , 184 ,  NOW(), NOW()),
(289, null , 186 ,  NOW(), NOW()),
(291, 'A', null ,  NOW(), NOW()),
(292, 'B', null ,  NOW(), NOW()),
(293, 'C', null ,  NOW(), NOW()),
(294, 'B', null ,  NOW(), NOW()),
(295, 'C', null ,  NOW(), NOW()),
(297, 'revolutionised', null ,  NOW(), NOW()),
(298, 'Identical theory', null ,  NOW(), NOW()),
(299, 'sole credit', null ,  NOW(), NOW()),
(300, 'proved extremely controversial', null ,  NOW(), NOW()),
(301, 'of evolution', null ,  NOW(), NOW()),
(303, 'missing link', null ,  NOW(), NOW()),
(304, 'proof of', null ,  NOW(), NOW()),
(305, 'the skull', null ,  NOW(), NOW()),
(306, 'so convincing', null ,  NOW(), NOW()),
(307, 'was declared', null ,  NOW(), NOW());


INSERT INTO question_answers (question_id, answer_text, option_id, created_at, updated_at)
VALUES
(310, 'FALSE', null ,  NOW(), NOW()),
(311, 'FALSE', null ,  NOW(), NOW()),
(312, 'TRUE', null ,  NOW(), NOW()),
(313, 'TRUE', null ,  NOW(), NOW()),
(314, 'NOT GIVEN', null ,  NOW(), NOW()),
(315, 'TRUE', null ,  NOW(), NOW()),
(316, 'NOT GIVEN', null ,  NOW(), NOW()),
(317, 'FALSE', null ,  NOW(), NOW()),
(319, 'develop new ideas', null ,  NOW(), NOW()),
(320, 'problem-solving', null ,  NOW(), NOW()),
(322, null , 191 ,  NOW(), NOW()),
(323, null , 194 ,  NOW(), NOW()),
(324, null , 200 ,  NOW(), NOW()),
(326, 'C', null ,  NOW(), NOW()),
(327, 'F', null ,  NOW(), NOW()),
(328, 'G', null ,  NOW(), NOW()),
(329, 'A', null ,  NOW(), NOW()),
(330, 'D', null ,  NOW(), NOW()),
(331, 'B', null ,  NOW(), NOW()),
(333, 'FALSE', null ,  NOW(), NOW()),
(334, 'TRUE', null ,  NOW(), NOW()),
(335, 'TRUE', null ,  NOW(), NOW()),
(336, 'FALSE', null ,  NOW(), NOW()),
(337, 'FALSE', null ,  NOW(), NOW()),
(338, 'NOT GIVEN', null ,  NOW(), NOW()),
(340, null , 204 ,  NOW(), NOW()),
(341, null , 206 ,  NOW(), NOW()),
(342, null , 210 ,  NOW(), NOW()),
(343, null , 213 ,  NOW(), NOW()),
(344, null , 218 ,  NOW(), NOW()),
(345, null , 222 ,  NOW(), NOW()),
(347, 'A', null ,  NOW(), NOW()),
(348, 'C', null ,  NOW(), NOW()),
(349, 'C', null ,  NOW(), NOW()),
(350, 'B', null ,  NOW(), NOW()),
(351, 'B', null ,  NOW(), NOW()),
(353, 'NOT GIVEN', null ,  NOW(), NOW()),
(354, 'FALSE', null ,  NOW(), NOW()),
(355, 'FALSE', null ,  NOW(), NOW()),
(356, 'TRUE', null ,  NOW(), NOW());